package com.example.testplugin.mapper;

import com.example.testplugin.model.TestUser;
import com.example.testplugin.model.TestUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TestUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    long countByExample(TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    int deleteByExample(TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    int insert(TestUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    int insertSelective(TestUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    List<TestUser> selectByExample(TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    TestUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    int updateByExampleSelective(@Param("row") TestUser row, @Param("example") TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    int updateByExample(@Param("row") TestUser row, @Param("example") TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    int updateByPrimaryKeySelective(TestUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Sun Jan 12 16:00:57 CST 2025
     */
    int updateByPrimaryKey(TestUser row);
}